import type { RouteModel, RoutesModel } from "./openapi";

export type { RoutesModel };

/** Header details shared with the content-type emitter. */
export interface EmitRoutesOptions {
	/** Where the schema came from, as the header records it. Keep it free of machine-specific paths. */
	source: string;
}

function renderRoute(route: RouteModel): string {
	const lines = [`\t\t${JSON.stringify(route.key)}: {`];
	if (route.pathParams !== undefined) lines.push(`\t\t\tparams: ${route.pathParams};`);
	if (route.query !== undefined) lines.push(`\t\t\tquery?: ${route.query};`);
	if (route.body !== undefined) lines.push(`\t\t\tbody: ${route.body};`);
	lines.push(`\t\t\tresponse: ${route.response};`, "\t\t};");
	return lines.join("\n");
}

/**
 * Renders the routes file: the document's component schemas as named types, and
 * a `StrapiRoutes` augmentation keyed by `"<METHOD> <path>"`.
 */
export function emitRoutes(model: RoutesModel, options: EmitRoutesOptions): string {
	const parts: string[] = [
		`// Generated by @fbritoferreira/strapi generate from ${options.source}. Do not edit.`,
		"/* eslint-disable */",
		"",
	];
	for (const schema of model.schemas) {
		parts.push(`/** Component schema \`${schema.name}\` of the OpenAPI document. */`, `export type ${schema.name} = ${schema.type};`, "");
	}
	if (model.routes.length > 0) {
		parts.push(
			'declare module "@fbritoferreira/strapi" {',
			"\tinterface StrapiRoutes {",
			...model.routes.map(renderRoute),
			"\t}",
			"}",
			""
		);
	}
	return parts.join("\n");
}
