import type { GraphqlModel } from "./graphql";

/** Header details shared with the other emitters. */
export interface EmitGraphqlOptions {
	source: string;
	generatedAt: Date;
}

/**
 * Renders the GraphQL schema as TypeScript: one exported type per object,
 * interface, enum, input object and union. Selection sets are not modelled —
 * annotate a query's result with the types you selected, or reach for
 * graphql-codegen when you want the selection itself typed.
 */
export function emitGraphql(model: GraphqlModel, options: EmitGraphqlOptions): string {
	const parts: string[] = [
		`// Generated by @fbritoferreira/strapi generate on ${options.generatedAt.toISOString()} from ${options.source}. Do not edit.`,
		"/* eslint-disable */",
		"",
	];
	const roots = [model.queryType, model.mutationType].filter((name): name is string => name !== undefined);
	if (model.types.length > 0 && roots.length > 0) {
		parts.push(`// Root operation types: ${roots.join(", ")}`, "");
	}
	for (const type of model.types) {
		parts.push(`/** GraphQL ${type.kind} \`${type.name}\`. */`, `export type ${type.name} = ${type.type};`, "");
	}
	return parts.join("\n");
}
