import type { Field, Model, TypeDecl } from "./normalize";

export interface EmitOptions {
	source: string;
	generatedAt: Date;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function propertyName(name: string): string {
	return IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

function renderField(field: Field): string[] {
	const lines: string[] = [];
	if (field.doc !== undefined) lines.push(`\t/** ${field.doc} */`);
	lines.push(`\t${propertyName(field.name)}${field.optional ? "?" : ""}: ${field.tsType};`);
	return lines;
}

function union(fields: Field[]): string {
	return fields.map((f) => JSON.stringify(f.name)).join(" | ");
}

function renderMarker(type: TypeDecl): string[] {
	const populatable = type.fields.filter((f) => f.populatable);
	if (populatable.length === 0) return [];
	const lines = [
		"\t/** Fields `populate` accepts. Type-level marker; Strapi never returns it. */",
		`\treadonly __populatable?: ${union(populatable)};`,
	];
	const relations = populatable.filter((f) => f.relation);
	if (relations.length > 0) {
		lines.push(
			"\t/** Fields written by reference rather than inline. Type-level marker. */",
			`\treadonly __relations?: ${union(relations)};`
		);
	}
	return lines;
}

function renderType(type: TypeDecl): string {
	const lines: string[] = [`/** ${type.doc} */`];
	if (type.kind === "component") {
		lines.push(`export interface ${type.name} {`, "\tid: number;");
	} else {
		lines.push(`export interface ${type.name} extends StrapiDocument {`);
		if (type.localized) lines.push("\tlocale: string;");
	}
	lines.push(...renderMarker(type));
	for (const field of type.fields) lines.push(...renderField(field));
	lines.push("}");
	return lines.join("\n");
}

function renderRegistry(model: Model): string | null {
	const blocks: string[] = [];
	if (model.collections.length > 0) {
		blocks.push("\tinterface StrapiContentTypes {", ...model.collections.map((c) => `\t\t${propertyName(c.key)}: ${c.typeName};`), "\t}");
	}
	if (model.singles.length > 0) {
		blocks.push("\tinterface StrapiSingleTypes {", ...model.singles.map((s) => `\t\t${propertyName(s.key)}: ${s.typeName};`), "\t}");
	}
	if (blocks.length === 0) return null;
	return ['declare module "@fbritoferreira/strapi" {', ...blocks, "}"].join("\n");
}

export function emit(model: Model, options: EmitOptions): string {
	const imports = ["StrapiDocument"];
	if (model.usesBlocks) imports.push("StrapiBlock");
	if (model.usesMedia) imports.push("StrapiMedia");
	if (model.usesUser) imports.push("StrapiUser");
	imports.sort();

	const parts: string[] = [
		`// Generated by @fbritoferreira/strapi generate on ${options.generatedAt.toISOString()} from ${options.source}. Do not edit.`,
		"/* eslint-disable */",
		"",
		`import type { ${imports.join(", ")} } from "@fbritoferreira/strapi";`,
		"",
	];
	for (const type of model.types) parts.push(renderType(type), "");
	const registry = renderRegistry(model);
	if (registry !== null) parts.push(registry, "");
	return parts.join("\n");
}
