// Generated by @fbritoferreira/strapi generate on 2026-09-20T10:00:00.000Z from fixture project. Do not edit.
/* eslint-disable */

import type { StrapiBlock, StrapiDocument, StrapiMedia, StrapiUser } from "@fbritoferreira/strapi";

/** Component blocks.hero (Hero) */
export interface BlocksHero {
	id: number;
	/** Fields `populate` accepts. Type-level marker; Strapi never returns it. */
	readonly __populatable?: "image";
	/** string */
	title: string;
	/** string */
	subtitle?: string;
	/** media */
	image?: StrapiMedia | null;
}

/** Component blocks.quote (Quote) */
export interface BlocksQuote {
	id: number;
	/** text */
	text: string;
	/** string */
	author?: string;
}

/** Component shared.seo (Seo) */
export interface SharedSeo {
	id: number;
	/** Fields `populate` accepts. Type-level marker; Strapi never returns it. */
	readonly __populatable?: "shareImage";
	/** string */
	metaTitle: string;
	/** text */
	metaDescription?: string;
	/** media */
	shareImage?: StrapiMedia | null;
}

/** Collection type api::article.article (Article) */
export interface Article extends StrapiDocument {
	locale: string;
	/** Fields `populate` accepts. Type-level marker; Strapi never returns it. */
	readonly __populatable?: "cover" | "gallery" | "author" | "tags" | "createdByUser" | "seo" | "blocks";
	/** string */
	title: string;
	/** uid */
	slug: string;
	/** blocks */
	body?: StrapiBlock[];
	/** text */
	summary?: string;
	/** integer */
	readingTime?: number;
	/** decimal */
	price?: number;
	/** biginteger (serialized as string) */
	views?: string;
	/** boolean */
	featured: boolean;
	/** date */
	publishedOn?: string;
	/** json */
	metadata?: unknown;
	/** enumeration */
	status: "draft" | "review" | "live";
	/** media */
	cover?: StrapiMedia | null;
	/** media (multiple) */
	gallery?: StrapiMedia[];
	/** relation manyToOne → api::author.author */
	author?: Author | null;
	/** relation manyToMany → api::tag.tag */
	tags?: Tag[];
	/** relation oneToOne → plugin::users-permissions.user */
	createdByUser?: StrapiUser | null;
	/** component shared.seo */
	seo?: SharedSeo | null;
	/** dynamiczone */
	blocks?: Array<(BlocksHero & { __component: "blocks.hero" }) | (BlocksQuote & { __component: "blocks.quote" })>;
}

/** Collection type api::author.author (Author) */
export interface Author extends StrapiDocument {
	/** Fields `populate` accepts. Type-level marker; Strapi never returns it. */
	readonly __populatable?: "avatar" | "articles" | "links";
	/** string */
	name: string;
	/** email */
	email?: string;
	/** media */
	avatar?: StrapiMedia | null;
	/** relation oneToMany → api::article.article */
	articles?: Article[];
	/** component shared.seo (repeatable) */
	links?: SharedSeo[];
}

/** Single type api::homepage.homepage (Homepage) */
export interface Homepage extends StrapiDocument {
	locale: string;
	/** Fields `populate` accepts. Type-level marker; Strapi never returns it. */
	readonly __populatable?: "hero" | "featuredArticle";
	/** string */
	heading: string;
	/** component blocks.hero */
	hero?: BlocksHero | null;
	/** relation oneToOne → api::article.article */
	featuredArticle?: Article | null;
}

/** Collection type api::tag.tag (Tag) */
export interface Tag extends StrapiDocument {
	/** string */
	label: string;
	/** string */
	color?: string;
}

declare module "@fbritoferreira/strapi" {
	interface StrapiContentTypes {
		articles: Article;
		authors: Author;
		tags: Tag;
	}
	interface StrapiSingleTypes {
		homepage: Homepage;
	}
}
