import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { emit } from "../../cli/emit";
import { loadFromDir } from "../../cli/load-dir";
import { normalize, type Model } from "../../cli/normalize";

const project = fileURLToPath(new URL("../../cli/__fixtures__/project", import.meta.url));
const snapshotFile = fileURLToPath(new URL("../../cli/__fixtures__/expected-output.ts", import.meta.url));
const generatedAt = new Date("2026-09-20T10:00:00.000Z");

describe("emit", () => {
	it("matches the committed snapshot for the fixture project", async () => {
		const output = emit(normalize(await loadFromDir(project), { includePlugins: false }), { source: "fixture project", generatedAt });
		if (process.env["UPDATE_SNAPSHOT"] === "1") await writeFile(snapshotFile, output);
		expect(output).toBe(await readFile(snapshotFile, "utf8"));
	});

	it("starts with the header and a minimal import", () => {
		const model: Model = { types: [], collections: [], singles: [], usesMedia: false, usesUser: false, usesBlocks: false };
		const out = emit(model, { source: "x", generatedAt });
		expect(out.split("\n")[0]).toBe("// Generated by @fbritoferreira/strapi generate on 2026-09-20T10:00:00.000Z from x. Do not edit.");
		expect(out).toContain('import type { StrapiDocument } from "@fbritoferreira/strapi";');
		expect(out).not.toContain("declare module");
	});

	it("emits locale as required on localized content types and id on components", () => {
		const model: Model = {
			types: [
				{ name: "SharedSeo", kind: "component", uid: "shared.seo", localized: false, fields: [{ name: "t", tsType: "string", optional: false, populatable: false, relation: false, doc: "string" }], doc: "Component shared.seo (Seo)" },
				{ name: "Page", kind: "single", uid: "api::page.page", localized: true, fields: [{ name: "seo", tsType: "SharedSeo | null", optional: true, populatable: false, relation: false }], doc: "Single type api::page.page (Page)" },
			],
			collections: [],
			singles: [{ key: "page", typeName: "Page" }],
			usesMedia: false,
			usesUser: false,
			usesBlocks: false,
		};
		const out = emit(model, { source: "x", generatedAt });
		expect(out).toContain("export interface SharedSeo {\n\tid: number;\n\t/** string */\n\tt: string;\n}");
		expect(out).toContain("export interface Page extends StrapiDocument {\n\tlocale: string;\n\tseo?: SharedSeo | null;\n}");
		expect(out).toContain('declare module "@fbritoferreira/strapi" {\n\tinterface StrapiSingleTypes {\n\t\tpage: Page;\n\t}\n}');
		expect(out).not.toContain("StrapiContentTypes");
	});

	it("lists populatable fields on a marker property", () => {
		const model: Model = {
			types: [
				{
					name: "Article",
					kind: "collection",
					uid: "api::article.article",
					localized: false,
					fields: [
						{ name: "title", tsType: "string", optional: false, populatable: false, relation: false },
						{ name: "author", tsType: "Author | null", optional: true, populatable: true, relation: true },
						{ name: "tags", tsType: "Tag[]", optional: true, populatable: true, relation: true },
					],
					doc: "Collection type api::article.article (Article)",
				},
			],
			collections: [{ key: "articles", typeName: "Article" }],
			singles: [],
			usesMedia: false,
			usesUser: false,
			usesBlocks: false,
		};
		expect(emit(model, { source: "x", generatedAt })).toContain('\treadonly __populatable?: "author" | "tags";');
	});

	it("lists relation and media fields on a second marker", () => {
		const model: Model = {
			types: [
				{
					name: "Article",
					kind: "collection",
					uid: "api::article.article",
					localized: false,
					fields: [
						{ name: "author", tsType: "Author | null", optional: true, populatable: true, relation: true },
						{ name: "seo", tsType: "SharedSeo | null", optional: true, populatable: true, relation: false },
					],
					doc: "Collection type api::article.article (Article)",
				},
			],
			collections: [{ key: "articles", typeName: "Article" }],
			singles: [],
			usesMedia: false,
			usesUser: false,
			usesBlocks: false,
		};
		const out = emit(model, { source: "x", generatedAt });
		expect(out).toContain('\treadonly __populatable?: "author" | "seo";');
		expect(out).toContain('\treadonly __relations?: "author";');
	});

	it("omits the relations marker when a type has only components", () => {
		const model: Model = {
			types: [
				{
					name: "Page",
					kind: "single",
					uid: "api::page.page",
					localized: false,
					fields: [{ name: "seo", tsType: "SharedSeo | null", optional: true, populatable: true, relation: false }],
					doc: "Single type api::page.page (Page)",
				},
			],
			collections: [],
			singles: [{ key: "page", typeName: "Page" }],
			usesMedia: false,
			usesUser: false,
			usesBlocks: false,
		};
		expect(emit(model, { source: "x", generatedAt })).not.toContain("__relations");
	});

	it("omits the marker when nothing is populatable", () => {
		const model: Model = {
			types: [
				{
					name: "Tag",
					kind: "collection",
					uid: "api::tag.tag",
					localized: false,
					fields: [{ name: "label", tsType: "string", optional: false, populatable: false, relation: false }],
					doc: "Collection type api::tag.tag (Tag)",
				},
			],
			collections: [{ key: "tags", typeName: "Tag" }],
			singles: [],
			usesMedia: false,
			usesUser: false,
			usesBlocks: false,
		};
		expect(emit(model, { source: "x", generatedAt })).not.toContain("__populatable");
	});

	it("quotes field names that are not identifiers", () => {
		const model: Model = {
			types: [{ name: "T", kind: "collection", uid: "api::t.t", localized: false, fields: [{ name: "kebab-case", tsType: "string", optional: true, populatable: false, relation: false }], doc: "d" }],
			collections: [{ key: "ts", typeName: "T" }],
			singles: [],
			usesMedia: false,
			usesUser: false,
			usesBlocks: false,
		};
		expect(emit(model, { source: "x", generatedAt })).toContain('\t"kebab-case"?: string;');
	});
});
