import { describe, expect, it } from "vitest";

import { emitGraphql } from "../../cli/emit-graphql";
import type { GraphqlModel } from "../../cli/graphql";

const generatedAt = new Date("2026-09-20T10:00:00.000Z");
const model: GraphqlModel = {
	queryType: "Query",
	mutationType: "Mutation",
	types: [
		{ name: "Article", kind: "OBJECT", type: "{\n\tdocumentId: string;\n}" },
		{ name: "PublicationStatus", kind: "ENUM", type: '"DRAFT" | "PUBLISHED"' },
	],
};

describe("emitGraphql", () => {
	const out = emitGraphql(model, { source: "http://h/graphql", generatedAt });

	it("starts with the generated header", () => {
		expect(out.split("\n")[0]).toBe("// Generated by @fbritoferreira/strapi generate on 2026-09-20T10:00:00.000Z from http://h/graphql. Do not edit.");
	});

	it("emits one exported type per schema type, labelled with its kind", () => {
		expect(out).toContain("/** GraphQL OBJECT `Article`. */\nexport type Article = {\n\tdocumentId: string;\n};");
		expect(out).toContain('/** GraphQL ENUM `PublicationStatus`. */\nexport type PublicationStatus = "DRAFT" | "PUBLISHED";');
	});

	it("names the root operation types", () => {
		expect(out).toContain("// Root operation types: Query, Mutation");
	});

	it("handles a schema with no types", () => {
		const empty = emitGraphql({ types: [] }, { source: "s", generatedAt });
		expect(empty).not.toContain("export type");
		expect(empty).not.toContain("Root operation types");
	});
});
