import { describe, expect, it } from "vitest";

import { emitRoutes, type RoutesModel } from "../../cli/emit-routes";

const model: RoutesModel = {
	schemas: [{ name: "PluginUploadFileDocument", type: "{ id: number; url: string }" }],
	routes: [
		{ key: "GET /files", method: "GET", path: "/files", query: "{ sort?: string }", response: "PluginUploadFileDocument[]" },
		{ key: "GET /files/{id}", method: "GET", path: "/files/{id}", pathParams: "{ id: string }", response: "PluginUploadFileDocument" },
		{ key: "POST /auth/local", method: "POST", path: "/auth/local", body: "{ identifier: string; password: string }", response: "{ jwt: string }" },
	],
};

describe("emitRoutes", () => {
	const out = emitRoutes(model, { source: "spec.json" });

	it("starts with the generated header", () => {
		expect(out.split("\n")[0]).toBe("// Generated by @fbritoferreira/strapi generate from spec.json. Do not edit.");
	});

	it("emits each component schema as a named type", () => {
		expect(out).toContain("export type PluginUploadFileDocument = { id: number; url: string };");
	});

	it("augments StrapiRoutes with one entry per route", () => {
		expect(out).toContain('declare module "@fbritoferreira/strapi" {');
		expect(out).toContain('\t\t"GET /files": {\n\t\t\tquery?: { sort?: string };\n\t\t\tresponse: PluginUploadFileDocument[];\n\t\t};');
	});

	it("makes path params and bodies required", () => {
		expect(out).toContain('\t\t"GET /files/{id}": {\n\t\t\tparams: { id: string };\n\t\t\tresponse: PluginUploadFileDocument;\n\t\t};');
		expect(out).toContain('\t\t\tbody: { identifier: string; password: string };');
	});

	it("emits nothing but the header when there are no routes", () => {
		const empty = emitRoutes({ schemas: [], routes: [] }, { source: "s" });
		expect(empty).not.toContain("declare module");
	});
});
